apiVersion: apps/v1
kind: Deployment
metadata:
  name: personskills-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personskills
  template:
    metadata:
      labels:
        app: personskills
    spec:
      containers:
      - name: personskills
        image: <DOCKERHUB_USERNAME>/personskills:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/personskills?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true