apiVersion: apps/v1
kind: Deployment
metadata:
  name: personskills-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personskills
  template:
    metadata:
      labels:
        app: personskills
    spec:
      containers:
      - name: personskills
        image: <DOCKERHUB_USERNAME>/personskills:latest
        ports:
        - containerPort: 8080